config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users do
    #get 'trips/behind', to: 'trips#behind'
    resources :todolists
    resources :trips, only: [:index]
  end

  resources :todolists
  resources :listings, only: [:destroy]
  resources :trips do
    resources :listings, except: [:index, :destroy]
  end
  resources :categories, only: [:index, :trip]
  resources :countries, only: [:index, :trip]
  get '/search', to: 'trips#search'
  get '/auth/google/callback', to: 'users#google_login'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :listings
  has_many :todolists, through: :listings
  has_many :users, through: :listings
  has_many :trip_categories
  has_many :categories, through: :trip_categories
  belongs_to :country

  validates :title, presence: true, uniqueness: { scope: :country_id } # Validates uniqueness of title and channel
  #validates :season, presence: true, uniqueness: { greater_than: 0 }

  scope :search, -> (query) { where("title LIKE ?", "%" + query + "%") }
  #scope :behind_on, -> (user_id) { joins(:listings).where('trips.season > listings.user_season').where(listings: {user_id: user_id}).uniq }

  def country_attributes=(country_attributes)
    country_attributes.values.each do |country_attribute|
      unless country_attribute.blank?
        country = Country.find_or_create_by(name: country_attribute)
        self.country = country
      end
    end
  end

  def categories_attributes=(category_attributes)
    category_name = category_attributes["0"]["name"]
    unless category_name.blank?
      category = Category.find_or_create_by(name: category_name)
      self.categories << category
    end
  end

  def trips_todolists_by_user(user_id)
    self.listings.where(user_id: user_id)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :require_login
  before_action :set_trip, only: [:show, :edit, :update]
  before_action :created_by_current_user, only: [:edit, :update]
  helper_method :current_user

  def index
    @user = User.find_by(id: params[:user_id])
    if @user
      @trips = @user.trips.uniq
    else
      @trips = Trip.all
    end
  end

  def trip
    @listings = @trip.trips_todolists_by_user(current_user.id)
  end

  def new
    @trip = Trip.new
    @listings = @trip.listings.build
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      flash[:message] = "#{@trip.title} has been created"
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @trip.update(trip_params)
    if @trip.save
      flash[:message] = "#{@trip.title} has been updated"
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def search
    @trips = Trip.search(params[:query])
    render :index
  end

  #def behind
  #  @trips = Trip.behind_on(params[:user_id])
  #  render :index
  #end

  private
  def trip_params
    params.require(:trip).permit( :title,
                                  :description,
                                  :country_id,
                                  :day,
                                  :time,
                                  :season,
                                  :created_by,
                                  category_ids:[],
                                  categories_attributes:[:name],
                                  country_attributes:[:name])
  end

  def set_trip
    @trip = Trip.find_by(id: params[:id])
  end

  def created_by_current_user
    unless @trip.created_by == current_user.id
      flash[:danger] = "You cannot edit this trip because you did not create it!"
      redirect_to trip_path(@trip)
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
  def todolist_options(listings, trip)
    if @listings.count > 0
      render :partial => "listings/details", :locals => {:listings => listings, :trip => trip}
    else
      "None"
    end
  end
end

app/views/trips/_form.html.erb
<% if @trip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
    <% @trip.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(trip) do |f| %>
  <strong><%= f.label :title %></strong>
  <%= f.text_field :title, class:"form-control" %><br>

  <strong><%= f.label "Show Description" %></strong>
  <%= f.text_area :description, class:"form-control" %><br>

  <div class="form-group">
    <strong><%= f.label :country %></strong><br>
    <%= f.collection_select :country_id, alphebetize(Country.all), :id, :name, :include_blank => true%> or new:
    <%= f.fields_for :country_attributes do |country_fields| %>
      <%= country_fields.text_field :name %>
    <% end %>
  </div>

  <strong><%= f.label :season %><br></strong>
  <%= f.number_field :season, class:"form-control" %><br>

  <div class="form-group">
    <strong><%= f.label :category %></strong><br>
    <%= f.collection_check_boxes(:category_ids, alphebetize(Category.all), :id, :name) do |b| %>
      <div class="form-check form-check-inline">
        <%= b.check_box(class: "form-check-input") %>
        <%= b.object.name %>
      </div>
    <% end %>
    or new:
    <%= f.fields_for :categories, trip.categories.build do |category_fields| %>
      <%= category_fields.text_field :name %>
    <% end %>
  </div>

  <strong><%= f.label :day %></strong>
  <%= f.text_field :day, class:"form-control" %>
  <br>

  <strong><%= f.label :time %></strong>
  <%= f.text_field :time, class:"form-control" %><br>

  <%= f.hidden_field :created_by, value: current_user.id %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/trips/_trips.html.erb
<table class="table table-striped table-hover table-light">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Country</th>
      <th scope="col">Season</th>
      <th scope="col">Categories</th>
    </tr>
  </thead>
  <tbody>
    <% alphebetize(trips).each do |trip| %>
      <tr>
        <th scope="row"><%= link_to trip.title, trip_path(trip) %></th>
        <td><%= trip.country.name %></td>
        <td><%= trip.season %></td>
        <td><%= trip.categories.map { |category| category.name }.join(', ') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trips/edit.html.erb
<% content_for :header do %>
  <h1>Edit <%= @trip.title %></h1>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    <li class="nav-item mb-3">
      <%= button_to "Back to #{@trip.title}", trip_path(@trip), :method => "get", class: "btn btn-info btn-block" %>
    </li>
    <li class="nav-item mb-3">
      <%= button_to "View All Trips", trips_path, :method => "get", class: "btn btn-info btn-block" %>
    </li>
  </ul>
<% end %>

<% content_for :content do %>
  <%= render partial: "form", locals: {trip: @trip} %>
<% end %>

app/views/trips/index.html.erb
<% content_for :header do %>
  <h1><%= link_to "Browse Trips", trips_path %></h1>
<% end %>

<% content_for :vertical_nav do %>
<ul class="nav flex-column">
  <li class="nav-item mb-3">
    <%= button_to "Add New Trip", new_trip_path, :method => "get", class: "btn btn-info btn-block" %>
  </li>
  <li class="nav-item">
    <%= button_to "Back to my To-Do lists", user_todolists_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
  </li>
</ul>
<% end %>

<% content_for :content do %>
  <%= render partial: "trips", locals: {trips: @trips} %>
<% end %>

<% content_for :sidebar do %>
  <%= form_tag("/search", method: "get") do %>
    <%= label_tag :query, "Search by Title:" %>
    <%= text_field_tag :query, "", class:"form-control" %>
    <%= submit_tag "Search", class: "btn btn-sm btn-secondary" %>
  <% end %>
  <br>
  <p>Browse By:
  <div class="btn-group" role="group">
    <%= button_to "Category", categories_path, :method => "get", class: "btn btn-outline-secondary" %>
    <%= button_to "Country", countries_path, :method => "get", class: "btn btn-outline-secondary" %>
  </div>
  </p>
<% end %>

app/views/trips/new.html.erb
<% content_for :header do %>
  <h1>Create a New Trip</h1>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    <li class="nav-item mb-3">
      <%= button_to "Back to Trips", trips_path, :method => "get", class: "btn btn-info btn-block" %>
    </li>
  </ul>
<% end %>

<% content_for :content do %>
  <%= render partial: "form", locals: {trip: @trip} %>
<% end %>

app/views/trips/show.html.erb
<% content_for :header do %>
  <h1><%= @trip.title %></h1>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    <li class="nav-item mb-3">
      <%= button_to "Back to Trips", trips_path, :method => "get", class: "btn btn-info btn-block" %>
    </li>
    <% if @trip.created_by == current_user.id %>
      <li class="nav-item mb-3">
        <%= button_to "Update trip details", edit_trip_path(@trip), :method => "get", class: "btn btn-info btn-block" %>
      </li>
    <% end %>
    <li class="nav-item">
      <%= button_to "Add to A To-Do List", new_trip_listing_path(@trip), :method => "get", class: "btn btn-info btn-block" %>
    </li>
  </ul>
<% end %>

<% content_for :content do %>
  <p><%= @trip.description %></p>
  <p><strong>Country</strong>: <%= link_to @trip.country.name, countries_path(@trip.country) %></p>
  <p><strong>Season</strong>: <%= @trip.season %></p>
  <p><strong>Categories</strong>: <%= @trip.categories.map { |category| link_to(category.name, categories_path(category)) }.join(', ').html_safe %></p>
  <p><strong>Day</strong>: <%= @trip.day %></p>
  <p><strong>Time</strong>: <%= @trip.time %></p>
<% end %>

<% content_for :sidebar do %>
  <h4>My To-Do Lists</h4>
  <%= todolist_options(@listings, @trip) %>
<% end %>