config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users do
    #get 'trips/behind', to: 'trips#behind'
    resources :todolists
    resources :trips, only: [:index]
  end

  resources :todolists
  resources :listings, only: [:destroy]
  resources :trips do
    resources :listings, except: [:index, :destroy]
  end
  resources :categories, only: [:index, :trip]
  resources :countries, only: [:index, :trip]
  get '/search', to: 'trips#search'
  get '/auth/google/callback', to: 'users#google_login'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :todolist
  belongs_to :trip
  belongs_to :user

  validates :user_season, presence: true, numericality: { greater_than: 0 }
  validates :todolist_id, uniqueness: { scope: :trip_id }, :on => :create
  #validate :user_season_vs_season

  #def user_season_vs_season
  #  if user_season.present? && user_season > show.current_season
  #    errors.add(:user_season, "can't be ahead of the show's Season #{show.current_season}")
  #  end
  #end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :require_login
  before_action :set_listing, only: [:edit, :update, :destroy]

  def new
    @listing = Listing.new
    @listing.trip = Trip.find_by(id: params[:trip_id])
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.trip = Trip.find_by(id: params[:trip_id])
    if @listing.save
      flash[:message] = "#{@listing.trip.title} has been added to your To-Do list"
      redirect_to trip_path(@listing.trip)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @listing.update(listing_params)
    if @listing.save
      flash[:message] = "#{@listing.trip.title} listing has been updated"
      redirect_to trip_path(@listing.trip)
    else
      render :edit
    end
  end

  def destroy
    if @listing
      @listing.destroy
      flash[:message] = "The trip has been removed from your To-Do list"
      redirect_to todolists_path
    else
      flash[:danger] = "The trip could not be removed"
      render 'trips/trip'
    end
  end

  private
  def listing_params
    params.require(:listing).permit(:todolist_id, :user_id, :user_status, :user_season, :fav)
  end

  def set_listing
    @listing = Listing.find_by(id: params[:id])
  end
end

app/views/listings/_details.html.erb
<% listings.each do |listing| %>
  <div class="card card-sm mb-3">
    <h5 class="card-header"><%= link_to listing.todolist.name, user_todolist_path(current_user, listing.todolist) %></h5>
    <div class="card-body">
      <p><strong>Your Status</strong>:<br>
        <%= listing.user_status %><br>
      <strong>Your Season</strong>: <%= listing.user_season %></p>
      <%= button_to "Edit To-Do List Details", edit_trip_listing_path(trip, listing), :method => "get", class: "btn btn-warning btn-sm btn-block" %>
      <%= form_for listing, method: :delete do |f| %>
        <%= f.submit "Remove From To-Do List", class:"btn btn-sm btn-danger btn-block" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/listings/_form.html.erb
<% if listing.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <ul>
    <% listing.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [trip, listing] do |f| %>
  <strong><%= f.label :todolist %></strong>
  <%= f.collection_select :todolist_id, alphebetize(current_user.todolists), :id, :name %><br>
  <strong><%= f.label :user_status %></strong>
  <%= f.text_field :user_status, class:"form-control" %><br>
  <strong><%= f.label :user_season %></strong>
  <%= f.number_field :user_season, class:"form-control" %><br>
  <%= f.check_box :fav %> <strong>Favorite?</strong> <br>
  <%= f.hidden_field :user_id, value: current_user.id %><br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/listings/edit.html.erb
<% content_for :header do %>
  <h1>Edit <%= @listing.trip.title %> on '<%= @listing.todolist.name %>' To-Do List</h1>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    <li class="nav-item mb-3">
      <%= button_to "Back to #{@listing.trip.title}", trip_path(@listing.trip), :method => "get", class: "btn btn-info btn-block" %>
    </li>
  </ul>
<% end %>

<% content_for :content do %>
  <%= render partial: "form", locals: {listing: @listing, trip: @listing.trip} %>
<% end %>

app/views/listings/new.html.erb
<% content_for :header do %>
  <h1>Add <%= @listing.trip.title %> to Your To-Do List</h1>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    <li class="nav-item mb-3">
      <%= button_to "Back to #{@listing.trip.title}", trip_path(@listing.trip), :method => "get", class: "btn btn-info btn-block" %>
    </li>
  </ul>
<% end %>

<% content_for :content do %>
  <%= render partial: "form", locals: {listing: @listing, trip: @listing.trip} %>
<% end %>