config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users do
    #get 'trips/behind', to: 'trips#behind'
    resources :todolists
    resources :trips, only: [:index]
  end

  resources :todolists
  resources :listings, only: [:destroy]
  resources :trips do
    resources :listings, except: [:index, :destroy]
  end
  resources :categories, only: [:index, :trip]
  resources :countries, only: [:index, :trip]
  get '/search', to: 'trips#search'
  get '/auth/google/callback', to: 'users#google_login'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/todolist.rb
class Todolist < ApplicationRecord
  belongs_to :user
  has_many :listings
  has_many :trips, through: :listings

  validates :name, presence: true

  before_destroy :destroy_listings

  private
  def destroy_listings
    self.listings.each do |listing|
      listing.destroy
    end
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :require_login
  before_action :set_user_todolist, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  def index
    @todolists = current_user.todolists
    @favorites = current_user.favorite_trips
  end

  def new
    @todolist = Todolist.new
  end

  def create
    @todolist = @user.todolists.build(todolist_params)
    if @todolist.save
      redirect_to todolist_path(@todolist)
      flash[:message] = "New To-Do List Created!"
    else
      render :new
    end
  end

  def trip
    @trips = @todolist.trips
  end

  def edit
  end

  def update
    @todolist.update(todolist_params)
    if @todolist.save
      redirect_to todolist_path(@todolist)
      flash[:message] = "#{@todolist.name} updated!"
    else
      render :edit
    end
  end

  def destroy
    if @todolist
      @todolist.destroy
      redirect_to todolists_path
      flash[:message] = "Your To-Do list has been deleted"
    else
      render :trip
      flash[:danger] = "This To-Do list could not be deleted"
    end
  end

  private
  def todolist_params
    params.require(:todolist).permit(:name, :description, :user_id)
  end

  def set_user_todolist
    @todolist = Todolist.find_by(id: params[:id])
    unless @todolist.user == current_user
      flash[:danger] = "This is not your To-Do list!"
      redirect_to todolists_path
    end
  end

  def set_user
    @user = User.find_by(id: params[:user_id])
  end
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/todolists/_form.html.erb
<% if todolist.errors.any? %>
<div class="alert alert-danger" role="alert">
  <ul>
      <% todolist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
  </ul>
</div>
<% end %>

<%= form_for [user, todolist] do |f| %>
  <strong><%= f.label :name %></strong>
  <%= f.text_field :name, class:"form-control" %><br>
  <strong><%= f.label :description %></strong>
  <%= f.text_area :description, class:"form-control" %><br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/todolists/edit.html.erb
<% content_for :header do %>
  <h1>Update <%= @todolist.name %> To-Do List</h1>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    <li class="nav-item mb-3">
      <%= button_to "Back to To-Do Lists", user_todolists_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
    </li>
  </ul>
<% end %>

<% content_for :content do %>
  <%= render partial: "form", locals: {user: @user, todolist: @todolist} %>
<% end %>

app/views/todolists/index.html.erb
<% content_for :header do %>
  <h1><%= current_user.username %>'s To-Do List</h1>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    <li class="nav-item mb-3">
      <%= button_to "Create a new To-Do List", new_user_todolist_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
    </li>
    <li class="nav-item mb-3">
      <%= button_to "Add a Trip", trips_path, :method => "get", class: "btn btn-info btn-block" %>
    </li>
    <!-- <li class="nav-item">
    <!--  form_tag(user_trips_behind_path(current_user), method: "get") do %> -->
    <!-- submit_tag("Trips I need to do:", class: "btn btn-warning btn-block") %> -->
      <!-- end %> -->
    <!-- </li> -->
  </ul>
<% end %>


<% content_for :content do %>
  <% if @todolists.count == 0 %>
    <p><center>You don't have any To-Do Lists! <%= link_to "Create One", new_user_todolist_path(current_user) %> to start adding trips!</center></p>
  <% else %>
    <% alphebetize(@todolists).each do |todolist| %>
      <div class="card border-info mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= link_to todolist.name, user_todolist_path(current_user, todolist) %></h5>
          <p class="card-text"><%= todolist.description %></p>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

<% content_for :sidebar do %>
  <p>Favorite Trips</p>
  <% @favorites.each do |trip| %>
    <p> <%= link_to trip.title, trip_path(trip) %></p>
  <% end %>
  <%= button_to "See All of My Trips", user_trips_path(current_user), :method => "get", class: "btn btn-info" %>
<% end %>

app/views/todolists/new.html.erb
<% content_for :header do %>
  <h1>Create a New To-Do List</h1>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    <li class="nav-item mb-3">
      <%= button_to "Back to To-Do Lists", user_todolists_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
    </li>
  </ul>
<% end %>

<% content_for :content do %>
  <%= render partial: "form", locals: {user: @user, todolist: @todolist} %>
<% end %>

app/views/todolists/show.html.erb
<% content_for :header do %>
  <h1><%= @todolist.name %></h1>
  <p><em><%= @todolist.description %></em></p>
<% end %>

<% content_for :vertical_nav do %>
  <ul class="nav flex-column">
    <li class="nav-item mb-3">
      <%= button_to "Edit this To-Do List", edit_user_todolist_path(current_user, @todolist), :method => "get", class: "btn btn-warning btn-block" %>
    </li>
    <li class="nav-item mb-3">
      <%= button_to "Back to All To-Do Lists", user_todolists_path(current_user), :method => "get", class: "btn btn-info btn-block" %>
    </li>
    <li class="nav-item">
      <%= button_to "Add Trips", trips_path, :method => "get", class: "btn btn-info btn-block" %>
    </li>
  </ul>
<% end %>

<% content_for :content do %>
  <% @trips.each do |trip| %>
      <div class="card mb-3">
        <h5 class="card-header"><%= link_to trip.title, trip_path(trip) %></h5>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Country: <%= trip.country.name %></li>
          <li class="list-group-item">Season: <%= trip.season %></li>
        </ul>
      </div>
  <% end %>
<% end %>

<% content_for :sidebar do %>
  <%= form_tag(todolist_path, method: "delete") do %>
    <%= submit_tag("Delete To-Do List", class: "btn btn-danger btn-block") %>
  <% end %>
<% end %>